import { crmRoutes } from './crm.js';
import type { FastifyPluginAsyncZod } from 'fastify-type-provider-zod';
import { systemRoutes } from './system.js';
import { authRoutes } from './auth.js';
import { iamRoutes } from './iam.js';
import { profileRoutes } from './profile.js';
import { profileAvatarRoutes } from './profile-avatar.js';
import { courtRoutes } from './courts.js';
import { publicRoutes } from './public.js';
import { notificationRoutes } from './notifications.js';
import { shopRoutes } from './shop.js';
import { categoryRoutes } from './categories.js';
import { uploadRoutes } from './uploads.js';
import { memberRoutes } from './members.js';
import { barRoutes } from './bar.js';
import { adminJobRoutes } from './admin-jobs.js';
import { bookingRoutes } from './bookings.js';
import { reportRoutes } from './reports.js';
import { shiftRoutes } from './shifts.js';
import { hrRoutes } from './hr.js';
import { financeRoutes } from './finance.js';
import { tenantRoutes } from './tenants.js';

export const v1Routes: FastifyPluginAsyncZod = async (fastify) => {
  await fastify.register(systemRoutes);
  await fastify.register(authRoutes);
  await fastify.register(iamRoutes);
  await fastify.register(profileRoutes);
  await fastify.register(profileAvatarRoutes);
  await fastify.register(courtRoutes);
  await fastify.register(publicRoutes);
  await fastify.register(notificationRoutes);
  await fastify.register(categoryRoutes);
  await fastify.register(uploadRoutes);
  await fastify.register(shopRoutes);
  await fastify.register(memberRoutes);
  await fastify.register(barRoutes);
  await fastify.register(adminJobRoutes);
  await fastify.register(bookingRoutes);
  await fastify.register(reportRoutes);
  await fastify.register(crmRoutes);
  await fastify.register(shiftRoutes);
  await fastify.register(hrRoutes);
  await fastify.register(financeRoutes);
  await fastify.register(tenantRoutes);
};
