import React from 'react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import plans from '@/mocks/plans.json';
import ClubSettingsPage from '../../../../../../../apps/web/src/app/(app)/admin/club/page';
const state = vi.hoisted(() => ({ permissions: ['admin:access', 'plans:update', 'courts:update'], plans: vi.fn(), save: vi.fn(), windows: vi.fn(), windowSave: vi.fn() }));
vi.mock('@/hooks/use-auth', () => ({ useAuth: () => ({ user: { id: 'owner' }, hasPermission: (permission: string) => state.permissions.includes(permission) }) }));
vi.mock('@/lib/api-client', () => ({ api: { plans: { list: state.plans } } }));
vi.mock('@/lib/club-settings-api', () => ({ clubSettingsApi: { updatePlan: state.save, windows: state.windows, updateWindow: state.windowSave } }));
vi.mock('@/components/club/bar-menu-settings', () => ({ BarMenuSettings: () => <p>Bar menu settings</p> }));
vi.mock('@/components/club/branding-editor', () => ({ BrandingEditor: () => <p>Branding editor</p> }));
vi.mock('@/components/club/domain-wizard', () => ({ DomainWizard: () => <p>Domain wizard</p> }));
function show() { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><ClubSettingsPage /></QueryClientProvider>); }
beforeEach(() => { state.permissions = ['admin:access', 'plans:update', 'courts:update']; state.plans.mockReset().mockResolvedValue(plans); state.save.mockReset().mockResolvedValue(plans[0]); state.windows.mockReset().mockResolvedValue([{ id: 'f0000000-0000-4000-8000-000000000001', weekday: 5, startsTime: '18:00', endsTime: '22:00', isActive: true }]); state.windowSave.mockReset().mockResolvedValue({}); });
describe('club settings screen', () => {
  it('does not fetch without admin access and hides edit without plan permission', async () => { state.permissions = []; const result = show(); expect(screen.getByText('Club settings are unavailable')).toBeInTheDocument(); expect(state.plans).not.toHaveBeenCalled(); result.unmount(); state.permissions = ['admin:access']; show(); await screen.findByText('Gold'); expect(screen.queryByRole('button', { name: 'Edit Gold' })).not.toBeInTheDocument(); });
  it('validates discounts and submits a plan edit', async () => { show(); fireEvent.click(await screen.findByRole('button', { name: 'Edit Gold' })); fireEvent.change(screen.getByLabelText('Court discount (%)'), { target: { value: '101' } }); fireEvent.click(screen.getByRole('button', { name: 'Save plan' })); await screen.findByRole('alert'); expect(state.save).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText('Court discount (%)'), { target: { value: '80' } }); fireEvent.click(screen.getByRole('button', { name: 'Save plan' })); await waitFor(() => expect(state.save).toHaveBeenCalledWith(plans[0].id, expect.objectContaining({ courtDiscountPct: 80 }))); });
  it('validates social time ordering and updates the active window', async () => { show(); fireEvent.mouseDown(screen.getByRole('tab', { name: 'Social windows' }), { button: 0, ctrlKey: false }); fireEvent.change(await screen.findByLabelText('Ends at'), { target: { value: '17:00' } }); fireEvent.click(screen.getByRole('button', { name: 'Save window' })); await screen.findByText('End time must be after start time'); expect(state.windowSave).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText('Ends at'), { target: { value: '21:00' } }); fireEvent.click(screen.getByLabelText('Active')); fireEvent.click(screen.getByRole('button', { name: 'Save window' })); await waitFor(() => expect(state.windowSave).toHaveBeenCalledWith('f0000000-0000-4000-8000-000000000001', expect.objectContaining({ isActive: false, endsTime: '21:00' }))); });
  it('does not expose social edits to an admin without court update permission', async () => { state.permissions = ['admin:access']; show(); fireEvent.mouseDown(screen.getByRole('tab', { name: 'Social windows' }), { button: 0, ctrlKey: false }); await screen.findByText(/Friday/); expect(screen.queryByRole('button', { name: 'Save window' })).not.toBeInTheDocument(); });
  it('offers branding and the domain wizard on a Website tab for admins', async () => { show(); fireEvent.mouseDown(screen.getByRole('tab', { name: 'Website' }), { button: 0, ctrlKey: false }); expect(await screen.findByText('Branding editor')).toBeInTheDocument(); expect(screen.getByText('Domain wizard')).toBeInTheDocument(); });
});
