import {beforeEach,describe,expect,it,vi} from 'vitest';
import {InvoiceDetailSchema,CreateInvoiceRequestSchema} from '@packages/validation';
vi.mock('@/lib/api-client',async()=>{const actual=await vi.importActual<typeof import('@/lib/api-client')>('@/lib/api-client');return{...actual,USE_MOCKS:true,mock:async<T,>(value:T)=>value};});
import{invoiceApi,resetInvoiceMocks}from'./invoice-api';
import fixture from '@/mocks/invoice-created.json';
import{mockMemberStore}from'./mock-members';
describe('invoice lifecycle',()=>{
 beforeEach(resetInvoiceMocks);
 it('creates a typed draft with integer paise lines and rejects ambiguous customers',async()=>{const invoice=await invoiceApi.create({memberId:mockMemberStore[0].id,lines:[{description:'Coaching',qty:2,unitPricePaise:12550}]});expect(invoice).toMatchObject({status:'DRAFT',totalPaise:25100,balancePaise:25100});expect(InvoiceDetailSchema.safeParse(await invoiceApi.get(invoice.id)).success).toBe(true);expect(CreateInvoiceRequestSchema.safeParse({memberId:mockMemberStore[0].id,businessClientId:'d1000000-0000-4000-8000-000000000001',lines:[{description:'Coaching',qty:1,unitPricePaise:1}]}).success).toBe(false);});
 it('sends drafts and records partial and final payments with matching balances',async()=>{expect((await invoiceApi.send(fixture.id)).status).toBe('SENT');const partial=await invoiceApi.pay(fixture.id,{method:'UPI',amountPaise:50000});expect(partial.invoice).toMatchObject({paidPaise:50000,balancePaise:100000,status:'SENT'});const final=await invoiceApi.pay(fixture.id,{method:'CARD'});expect(final.invoice).toMatchObject({balancePaise:0,status:'PAID'});expect((await invoiceApi.get(fixture.id)).payments).toHaveLength(2);await expect(invoiceApi.pay(fixture.id,{method:'CASH'})).rejects.toThrow();});
 it('rejects excessive payment and voiding paid invoices without changing balance',async()=>{await expect(invoiceApi.pay(fixture.id,{method:'CASH',amountPaise:200000})).rejects.toThrow();expect((await invoiceApi.get(fixture.id)).balancePaise).toBe(150000);await invoiceApi.pay(fixture.id,{method:'CASH',amountPaise:1});await expect(invoiceApi.void(fixture.id,{reason:'Mistake'})).rejects.toThrow();});
 it('voids only unpaid invoices and removes their open balance',async()=>{await expect(invoiceApi.void(fixture.id,{reason:''})).rejects.toThrow();expect((await invoiceApi.void(fixture.id,{reason:'Duplicate invoice'}))).toMatchObject({status:'VOID',balancePaise:0});await expect(invoiceApi.send(fixture.id)).rejects.toThrow();await expect(invoiceApi.get('missing')).rejects.toMatchObject({statusCode:404});});
 it('filters before paginating and supports business client invoices',async()=>{await invoiceApi.create({businessClientId:'d1000000-0000-4000-8000-000000000001',lines:[{description:'School coaching',qty:1,unitPricePaise:200000}]});expect((await invoiceApi.list({businessClientId:'d1000000-0000-4000-8000-000000000001',limit:1})).meta.totalItems).toBe(1);await invoiceApi.send(fixture.id);expect((await invoiceApi.list({status:'SENT'})).data).toHaveLength(1);});
});
