import { z } from 'zod';
import { InvoiceSchema, InvoiceDetailSchema, InvoicePageSchema, InvoiceListQuerySchema, CreateInvoiceRequestSchema, PayInvoiceRequestSchema, PayInvoiceResponseSchema, VoidInvoiceRequestSchema, BusinessClientPageSchema, type InvoiceDetail, type InvoiceListQuery, type CreateInvoiceRequest, type PayInvoiceRequest, type VoidInvoiceRequest } from '@packages/validation';
import { fetchApi, USE_MOCKS, mock, ApiError } from '@/lib/api-client';
import { mockMemberStore } from '@/lib/mock-members';
import fixture from '@/mocks/invoice-created.json';

const seed = InvoiceDetailSchema.parse({ ...fixture, payments: [] });
const invoices: InvoiceDetail[] = [structuredClone(seed)];
export function resetInvoiceMocks() { invoices.splice(0, invoices.length, structuredClone(seed)); }
function find(id: string) { const invoice = invoices.find((value) => value.id === id); if (!invoice) throw new ApiError('Invoice not found', 404, 'NOT_FOUND'); return invoice; }
function today() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(new Date()); }
function plusDays(value: string, days: number) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function queryString(params: object) { const query = new URLSearchParams(); Object.entries(params).forEach(([key,value]) => { if (value !== undefined) query.set(key, String(value)); }); return query.toString(); }
export const invoiceApi = {
  async list(params: Partial<InvoiceListQuery> = {}) { const query = InvoiceListQuerySchema.parse(params); if (!USE_MOCKS) return InvoicePageSchema.parse(await fetchApi(`/api/v1/invoices?${queryString(query)}`)); const data = invoices.filter((value) => (!query.status || value.status === query.status) && (!query.memberId || value.billTo.id === query.memberId) && (!query.businessClientId || value.billTo.id === query.businessClientId) && (!query.from || value.issueDate >= query.from) && (!query.to || value.issueDate <= query.to) && (query.overdue !== 'true' || (value.balancePaise > 0 && value.dueDate < today() && value.status !== 'VOID'))); return mock(InvoicePageSchema.parse({ data: data.slice((query.page-1)*query.limit, query.page*query.limit), meta: { page: query.page, limit: query.limit, totalItems: data.length, totalPages: Math.ceil(data.length/query.limit), hasPrevPage: query.page>1, hasNextPage: query.page*query.limit<data.length } })); },
  async get(id: string) { return USE_MOCKS ? mock(structuredClone(find(id))) : InvoiceDetailSchema.parse(await fetchApi(`/api/v1/invoices/${encodeURIComponent(id)}`)); },
  async clients() { return USE_MOCKS ? mock(BusinessClientPageSchema.parse({ data: [{ id: 'd1000000-0000-4000-8000-000000000001', companyName: 'Riverside School', contactName: 'Priya Shah', email: 'accounts@example.com', phone: null, gstin: null, billingAddress: '12 Riverside Road', openBalancePaise: 0 }], meta: { page:1,limit:100,totalItems:1,totalPages:1,hasPrevPage:false,hasNextPage:false } })) : BusinessClientPageSchema.parse(await fetchApi('/api/v1/business-clients?limit=100')); },
  async create(input: CreateInvoiceRequest) { const data = CreateInvoiceRequestSchema.parse(input); if (!USE_MOCKS) return InvoiceSchema.parse(await fetchApi('/api/v1/invoices', { method:'POST',body:JSON.stringify(data) })); const customer = data.memberId ? mockMemberStore.find((value) => value.id === data.memberId) : null; if (data.memberId && !customer) throw new ApiError('Member not found',404,'NOT_FOUND'); if (data.businessClientId && data.businessClientId !== 'd1000000-0000-4000-8000-000000000001') throw new ApiError('Business client not found',404,'NOT_FOUND'); const lines = data.lines.map((line) => ({ ...line,lineTotalPaise:line.qty*line.unitPricePaise })); const total = lines.reduce((sum,line) => sum+line.lineTotalPaise,0); const issueDate = data.issueDate ?? today(); const invoice = InvoiceDetailSchema.parse({ id:crypto.randomUUID(),invoiceNumber:`INV-${issueDate.slice(0,4)}-${String(invoices.length+1).padStart(4,'0')}`,status:'DRAFT',billTo:{ type:data.memberId?'MEMBER':'BUSINESS_CLIENT',id:data.memberId ?? data.businessClientId,name:customer?.fullName ?? 'Riverside School' },issueDate,dueDate:data.dueDate ?? plusDays(issueDate,15),lines,subtotalPaise:total,taxPaise:Math.round(total*18/118),totalPaise:total,paidPaise:0,balancePaise:total,notes:data.notes ?? null,payments:[] }); invoices.unshift(invoice); return mock(InvoiceSchema.parse(invoice)); },
  async send(id:string) { if (!USE_MOCKS) return InvoiceSchema.parse(await fetchApi(`/api/v1/invoices/${encodeURIComponent(id)}/send`,{ method:'POST' })); const invoice=find(id); if(invoice.status!=='DRAFT') throw new ApiError('Only draft invoices can be sent',409,'INVALID_INVOICE_STATUS'); invoice.status='SENT'; return mock(InvoiceSchema.parse(invoice)); },
  async pay(id:string,input:PayInvoiceRequest) { const data=PayInvoiceRequestSchema.parse(input); if (!USE_MOCKS) return PayInvoiceResponseSchema.parse(await fetchApi(`/api/v1/invoices/${encodeURIComponent(id)}/pay`,{ method:'POST',body:JSON.stringify(data) })); const invoice=find(id); const amount=data.amountPaise ?? invoice.balancePaise; if(invoice.status==='VOID' || invoice.status==='PAID' || amount>invoice.balancePaise || amount<=0) throw new ApiError('Payment must not exceed the open invoice balance',409,'INVALID_PAYMENT'); const payment={id:crypto.randomUUID(),amountPaise:amount,method:data.method}; invoice.paidPaise+=amount;invoice.balancePaise-=amount;if(invoice.balancePaise===0)invoice.status='PAID';invoice.payments.unshift({...payment,paidAt:new Date().toISOString()});return mock(PayInvoiceResponseSchema.parse({invoice,payment})); },
  async void(id:string,input:VoidInvoiceRequest) { const data=VoidInvoiceRequestSchema.parse(input); if(!USE_MOCKS)return InvoiceSchema.parse(await fetchApi(`/api/v1/invoices/${encodeURIComponent(id)}/void`,{method:'POST',body:JSON.stringify(data)})); const invoice=find(id);if(invoice.paidPaise>0 || invoice.status==='VOID')throw new ApiError('Only unpaid invoices can be voided',409,'INVALID_INVOICE_STATUS');invoice.status='VOID';invoice.balancePaise=0;return mock(InvoiceSchema.parse(invoice)); },
};
export type InvoicePage = z.infer<typeof InvoicePageSchema>;
